// AUTO-GENERATED BY ZOD-TO-TS. DO NOT EDIT DIRECTLY.
export type Invoice = {
    id: string;
    clientName: string;
    amount: number;
    taxRate: number;
    totalAmount: number;
    status: "draft" | "paid" | "void";
    createdAt: string;
    mascot?: string | undefined;
    [x: string]: never;
};
export type PaginatedResponse = {
    data: {
        id: string;
        clientName: string;
        amount: number;
        taxRate: number;
        totalAmount: number;
        status: "draft" | "paid" | "void";
        createdAt: string;
        mascot?: string | undefined;
        [x: string]: never;
    }[];
    meta: {
        page: number;
        limit: number;
        totalRecords: number;
        totalPages: number;
        [x: string]: never;
    };
    [x: string]: never;
};
