import { writeFileSync, mkdirSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";
import {
  printNode,
  zodToTs,
  createAuxiliaryTypeStore,
  createTypeAlias,
} from "zod-to-ts"; //
import {
  InvoiceContract,
  PaginatedInvoicesContract,
} from "../src/contracts.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

function generate() {
  const store = createAuxiliaryTypeStore();

  const { node: invoiceNode } = zodToTs(InvoiceContract, {
    auxiliaryTypeStore: store,
  });
  const { node: paginatedNode } = zodToTs(PaginatedInvoicesContract, {
    auxiliaryTypeStore: store,
  });

  const invoiceAlias = createTypeAlias(invoiceNode, "Invoice");
  const paginatedAlias = createTypeAlias(paginatedNode, "PaginatedResponse");

  const contractTypesContent = `// AUTO-GENERATED BY ZOD-TO-TS. DO NOT EDIT DIRECTLY.
export ${printNode(invoiceAlias)}
export ${printNode(paginatedAlias)}
`;

  const outputPath = join(__dirname, "../../client/src/types/api.d.ts");

  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, contractTypesContent, "utf-8");

  console.log(
    "🚀 API Contracts successfully synchronized to client/src/types/api.d.ts",
  );
}

generate();
